import type { components, operations, paths } from "./schema";
import type { ApiResponse } from "@/utils/http/types.d";

/**
 * Contract helpers over `schema.d.ts` (generated by `pnpm gen:api` from
 * `../ArchForge/spec/openapi.yaml` — itself generated by `./gradlew generateOpenApi`).
 *
 * Prefer these over hand-written `{...}` response types: the backend is the
 * single source of truth, and stale hand-written types are caught by typecheck
 * the moment the contract moves.
 */

export type { components, operations, paths };

/** A path that exists in the contract. */
export type ContractPath = keyof paths;

/** Component schema by name, e.g. `Schema<"LoginResponse">`. */
export type Schema<N extends keyof components["schemas"]> =
  components["schemas"][N];

type JsonContent<R> = R extends { content: infer C }
  ? C extends { "application/json": infer D }
    ? D
    : C extends { "*/*": infer D }
      ? D
      : never
  : never;

/**
 * The success-envelope type of a contract operation, e.g.
 * `OpResult<"/auth/login", "post">` = `ApiResponse<LoginResponse>`.
 *
 * The backend wraps controller returns in `{code,message,data}` at runtime
 * (ResultValueWrapper), so the generated 200 content is the *data* payload —
 * this helper re-wraps it in ApiResponse.
 */
/** If D is already a `{code,data}` envelope (ResponseResult*), unwrap data only. */
type Enveloped<D> = D extends { code: number; data: infer T }
  ? ApiResponse<T>
  : ApiResponse<D>;

export type OpResult<
  P extends ContractPath,
  M extends keyof paths[P]
> = paths[P][M] extends { responses: { 200: infer R } }
  ? Enveloped<JsonContent<R>>
  : never;

/** The request-body JSON type of a contract operation, e.g. `OpBody<"/auth/login", "post">` = `LoginRequest`. */
export type OpBody<
  P extends ContractPath,
  M extends keyof paths[P]
> = paths[P][M] extends { requestBody: infer B } ? JsonContent<B> : never;
